# Arthur zombieman

# Information
# %player% is the player that ran
# the command, %command% is the command
# that got run, %time% is how long
# it took to reload in milliseconds.
# %world% is what would the player was
# when they ran the command.

# The ignored commands has to be
# with a slash in the start,
# you can add a command in-game
# with /csp add-command <command>

# * gets replaced with '

# Hex code format: &#FFFFFF
# THE FORMAT WORKS WITH HEX CODES AND COLOR CODES!

# Format placeholders:
# Player's name: %player%
# Command: %command%
# Server Name: %server-name%
# World: %world%

format: '&#0084FF[%server-name%] &r&7→ &#0084FF%player%: &#0070D9%command%'

# FOR THE SERVER NAME TO WORK
# CROSS SERVER YOU NEED TO HAVE A
# WORKING REDIS DATABASE!
serverName: "Server Name"

# IF THIS PLACEHOLDER IS 0 THE USERNAME WILL NOT
# BE UPDATED ON JOIN, IF THE USER IS FOR EXAMPLE NICKED.
placeholder: "%example_isnicked%"

database:
  use: false
  mysql:
    username: username
    password: null
    url: example.com
  redis:
    channel: "CSP"
    host: example.com
    port: port
    username: username
    password: password1234

enabled: '&aCommand Spy Plus was enabled'
disabled: '&cCommand Spy Plus was disabled'

maxLogDays: 30

reload-message: '&bCommand Spy Plus was successfully reloaded &7(%time%ms)'
no-permission: '&cYou don*t have the permission to execute this command!'
ignored-commands:
  - '/cspadmin'

# Permissions:
# commandspyplus.command.main
# commandspyplus.command.cspadmin
# commandspyplus.event.see
# commandspyplus.event.hide

